apiVersion: batch/v1
kind: Job
metadata:
  name: health-job
spec:
  template:
    spec:
      containers:
        - name: client
          image: "yavosh/k8s-test-job:latest"
          command: ["curl", "-s",  "http://api-service:8080/health"]
      restartPolicy: Never
  backoffLimit: 4