apiVersion: v1
kind: Service
metadata:
  name: api-service-lb
  labels:
    app: api
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
      targetPort: 8080